export const config = { runtime: "nodejs", maxDuration: 60 };
const PRIVATE_HOSTS = new Set(["localhost","localhost.localdomain","ip6-localhost","ip6-loopback"]);
const HOP_BY_HOP = new Set(["connection","keep-alive","proxy-authenticate","proxy-authorization","te","trailer","transfer-encoding","upgrade"]);
const PASS_HEADERS = ["range","if-range","accept","accept-language","if-none-match","if-modified-since"];
const patternsFrom = value => String(value || "").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);
const configuredPatterns = () => patternsFrom(process.env.ALLOWED_STREAM_HOSTS);
function isPrivateHost(hostname) { const h=hostname.toLowerCase().replace(/[\[\]]/g,""); if(PRIVATE_HOSTS.has(h)||h.endsWith(".localhost")||h.endsWith(".local")) return true; if(/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||h==="0.0.0.0"||h==="::1"||h==="::") return true; if(/^[0-9a-f:]+$/i.test(h)&&h.includes(":")) { const first=parseInt(h.split(":")[0]||"0",16); if((first&0xfe00)===0xfc00||(first&0xffc0)===0xfe80) return true; } return false; }
export function isAllowedHost(url, patterns = configuredPatterns()) { if(!url?.hostname || isPrivateHost(url.hostname)||!patterns.length) return false; const host=url.hostname.toLowerCase(); return patterns.some(pattern=>pattern.startsWith("*.") ? host.endsWith(pattern.slice(1)) && host.length>pattern.length-1 : host===pattern); }
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...securityHeaders()}})}
function securityHeaders(){return {"x-content-type-options":"nosniff","referrer-policy":"no-referrer","content-security-policy":"default-src 'none'; frame-ancestors 'none'","permissions-policy":"camera=(), microphone=(), geolocation=()"};}
function gatewayUrl(target){return "/api/stream?url="+encodeURIComponent(target.href)}
export function rewriteM3U8(body,baseUrl,patterns=configuredPatterns()){const rewrite=raw=>{try{const absolute=new URL(raw,baseUrl);return ["http:","https:"].includes(absolute.protocol)&&isAllowedHost(absolute,patterns)?gatewayUrl(absolute):raw}catch{return raw}};return String(body).replace(/URI="([^"]+)"/g,(_,uri)=>`URI="${rewrite(uri)}"`).split(/\r?\n/).map(line=>{const t=line.trim();return !t||t.startsWith("#")?line:rewrite(t)}).join("\n")}
function withTimeout(signal,ms=25000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),ms); if(signal) signal.addEventListener("abort",()=>controller.abort(),{once:true}); return {signal:controller.signal,done:()=>clearTimeout(timer)};}
async function fetchAllowed(url,req,depth=0){if(depth>3||!isAllowedHost(url))throw new Error("Redirect target is not allowlisted"); const headers=new Headers(); for(const n of PASS_HEADERS){const v=req.headers.get(n);if(v)headers.set(n,v)} headers.set("user-agent","MovieCloud-MediaGateway/2.0"); const timeout=withTimeout(req.signal); try{const upstream=await fetch(url,{method:req.method,headers,redirect:"manual",signal:timeout.signal}); if([301,302,303,307,308].includes(upstream.status)){const location=upstream.headers.get("location");if(!location)return upstream;return fetchAllowed(new URL(location,url),req,depth+1)} return upstream;} finally{timeout.done()}}
export default async function handler(req){if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...securityHeaders(),"access-control-allow-origin":"*","access-control-allow-methods":"GET, HEAD, OPTIONS","access-control-allow-headers":"Range, Content-Type, If-Range"}}); if(req.method!=="GET"&&req.method!=="HEAD")return json({error:"Method not allowed"},405); const raw=new URL(req.url).searchParams.get("url");if(!raw)return json({error:"Missing url"},400); let target;try{target=new URL(raw)}catch{return json({error:"Invalid url"},400)} if(!["http:","https:"].includes(target.protocol))return json({error:"Only HTTP(S) media sources are supported"},400); if(target.username||target.password)return json({error:"Credential-bearing media URLs are not accepted"},400); if(!isAllowedHost(target))return json({error:"Source host is not allowlisted or is a private network target",hint:"Set ALLOWED_STREAM_HOSTS to explicitly authorized hostnames."},403); let upstream;try{upstream=await fetchAllowed(target,req)}catch{return json({error:"Upstream request failed or timed out"},502)} const contentType=(upstream.headers.get("content-type")||"").toLowerCase(), looksLikeHls=/\.m3u8(?:$|[?#])/i.test(target.pathname+target.search)||contentType.includes("mpegurl"); const out=new Headers();for(const [n,v] of upstream.headers)if(!HOP_BY_HOP.has(n.toLowerCase()))out.set(n,v);Object.entries(securityHeaders()).forEach(([n,v])=>out.set(n,v));out.set("access-control-allow-origin","*");out.set("access-control-expose-headers","Accept-Ranges,Content-Length,Content-Range,Content-Type,ETag,Last-Modified");out.set("cache-control","private, no-store"); if(looksLikeHls&&req.method==="GET"&&upstream.ok){const length=Number(upstream.headers.get("content-length")||0);if(length&&length>2_000_000)return json({error:"Manifest exceeds size limit"},413);try{const rewritten=rewriteM3U8(await upstream.text(),target);out.set("content-type","application/vnd.apple.mpegurl; charset=utf-8");out.delete("content-length");return new Response(rewritten,{status:upstream.status,statusText:upstream.statusText,headers:out})}catch{return json({error:"Malformed HLS manifest"},502)}} if(!out.has("accept-ranges"))out.set("accept-ranges","bytes"); return new Response(req.method==="HEAD"?null:upstream.body,{status:upstream.status,statusText:upstream.statusText,headers:out});}
