window.MOVIECLOUD_PROVIDER_DETAILS = {
  BasPlayFTP:{site:null,label:"BasPlayFTP",engine:"CloudStream Kotlin extractor",media:"Direct video sources",capabilities:["Search/catalog parsing","Movie & TV categories","Direct playback link extraction"],source:"BasPlayFTP/src/main/kotlin/com/movieflick/basplayftp/BasPlayFTP.kt",note:"The plugin contains the provider/network endpoints and playback parsing. Browser playback still needs an authorized direct media URL."},
  CinePlexFTP:{site:"http://cineplexbd.net",label:"CinePlexBD",engine:"CloudStream Kotlin extractor",media:"MP4 / HLS",capabilities:["Catalog parsing","Detail → player resolution","Direct media extraction"],source:"CinePlexFTP/src/main/kotlin/com/movieflick/cineplexftp/CinePlexFTP.kt",note:"The repository explicitly handles MP4/HLS playback URLs in the provider extractor."},
  CTGFTP:{site:"https://ctgmovies.com",label:"CTG Movies",engine:"CloudStream Kotlin extractor",media:"MP4 / HLS + subtitles",capabilities:["Search/catalog","Episode playback resolution","Serialized playback sources","Subtitle tracks"],source:"CTGFTP/src/main/kotlin/com/movieflick/ctgftp/CTGFTP.kt",note:"The provider resolves current watch-page playback sources at Play time."},
  DhakaFTP:{site:null,label:"DhakaFTP",engine:"CloudStream Kotlin FTP/HTTP extractor",media:"MP4 / HLS",capabilities:["Multi-library catalog","Movie & series grouping","Direct video URL extraction"],source:"DhakaFTP/src/main/kotlin/com/movieflick/dhakaftp/DhakaFTP.kt",note:"The plugin contains multiple network-library endpoints. They are intentionally not exposed as public web links here."},
  DiscoveryFTP:{site:"https://movies.discoveryftp.net",label:"Discovery Movies",engine:"CloudStream Kotlin extractor",media:"MP4 / HLS",capabilities:["Movie categories","Series categories","Anime categories","Direct media extraction"],source:"DiscoveryFTP/src/main/kotlin/com/movieflick/discoveryftp/DiscoveryFTP.kt",note:"The extractor contains multiple category/source paths and recognizes MP4/HLS media."},
  HiAnime:{site:"https://hianime.at",label:"HiAnime",engine:"CloudStream Kotlin + source mapper",media:"HLS / MP4",capabilities:["Anime search","Episode/source mapping","HLS/MP4 detection","Subtitle/source metadata"],source:"HiAnime/src/main/kotlin/com/movieflick/hianime/HiAnime.kt",note:"The repository has a dedicated source-mapping flow. This web UI does not reproduce that third-party resolver."},
  KhulnaPlex:{site:"http://khulnaplex.com",label:"KhulnaPlex",engine:"CloudStream Kotlin extractor",media:"MP4 / HLS",capabilities:["Catalog parsing","Direct video/source extraction","Download-source fallback"],source:"KhulnaPlex/src/main/kotlin/com/movieflick/khulnaplex/KhulnaPlex.kt",note:"The plugin resolves the current direct media URL when Play is requested."},
  MojaLoss:{site:"https://www.mojaloss.stream",label:"MojaLoss",engine:"CloudStream Kotlin extractor",media:"Provider player sources",capabilities:["Multi-source catalog","Movie player data","TV configuration","Fresh playback resolution"],source:"MojaLoss/src/main/kotlin/com/movieflick/mojaloss/MojaLoss.kt",note:"Playback data is refreshed at Play time by the Kotlin extractor."},
  MovieHaat:{site:"https://moviehaat.net",label:"MovieHaat",engine:"CloudStream Kotlin/API extractor",media:"Provider video sources",capabilities:["Multi-category catalog","Movie/series sources","API-backed source metadata"],source:"MovieHaat/src/main/kotlin/com/movieflick/moviehaat/MovieHaat.kt",note:"The repository defines multiple configured source categories and API endpoints."},
  MovieLinkBD:{site:"https://movielinkbd.tv",label:"MovieLinkBD",engine:"CloudStream Kotlin extractor",media:"Direct playable sources",capabilities:["Fresh player-data request","Multiple mirror fallback","Tokenized source parsing"],source:"MovieLinkBD/src/main/kotlin/com/movieflick/movielinkbd/MovieLinkBD.kt",note:"The plugin deliberately performs a fresh playback-data request for each Play action."},
  OnlineMovies:{site:"https://111.90.159.132",label:"OnlineMovies",engine:"CloudStream Kotlin extractor",media:"MP4 / HLS",capabilities:["Movie/TV catalog","Playback-page discovery","HLS master expansion","Quality-aware source selection"],source:"OnlineMovies/src/main/kotlin/com/movieflick/onlinemovies/OnlineMovies.kt",note:"The extractor discovers media candidates and can expand HLS master playlists."},
  YouTube:{site:"https://www.youtube.com",label:"YouTube",engine:"NewPipe-based CloudStream provider",media:"YouTube video streams",capabilities:["Search","Categories","Video metadata","Stream extraction inside CloudStream"],source:"YouTube/src/main/kotlin/com/movieflick/youtube/YouTube.kt",note:"The repository uses the CloudStream/NewPipe stack. This static web player does not reproduce that extractor."},
  YouTubeKids:{site:"https://www.youtube.com/kids",label:"YouTube Kids",engine:"NewPipe-based CloudStream provider",media:"YouTube video streams",capabilities:["Kids-focused search","Video filtering","Video metadata","CloudStream stream extraction"],source:"YouTubeKids/src/main/kotlin/com/movieflick/youtubekids/YouTubeKids.kt",note:"The provider uses the NewPipe extractor stack and is not executed by the static browser frontend."},
  Zoryva:{site:"https://zoryva.me",label:"Zoryva",engine:"CloudStream Kotlin extractor",media:"Direct / HLS / MP4 candidates",capabilities:["Fresh player-page resolution","Multiple server candidates","Direct media detection","Subtitle discovery"],source:"Zoryva/src/main/kotlin/com/zoryva/zoryva/Zoryva.kt",note:"The Kotlin provider performs source discovery and probing. This web UI only plays authorized direct media URLs."},
  MovieBox:{site:"https://movieboxonline.net",label:"MovieBox",engine:"CloudStream plugin wrapper",media:"Provider-dependent",capabilities:["CloudStream package","Provider metadata","Plugin-based playback"],source:"MovieBox/src/main/kotlin/com/movieflick/moviebox/MovieBox.kt",note:"MovieBox is currently published as a very small CS3 wrapper; the web player does not invent a separate resolver."}
};